# The CS2800 Calculator, by Zhac067

Welcome! Here are some simple instructions to use.

## To run
If you already have the runnable jar, either execute it from the desktop environment to use the JavaFX GUI,
or run it with `java -jar calculator-zhac067-1.2.jar` to use the command line interface.

If using maven, try one of the following:
* `mvn javafx:run`
* `mvn exec:java -D"exec.mainClass"="ac.uk.rhul.zhac067.calculator.Driver"`
* `mvn package` to generate a runnable jar

Note, make sure to use `calculator-zhac067-1.2.jar` 
and not `original-calculator-zhac067-1.2.jar` (which is generated by the maven Shade plugin).

## To calculate
You can change the calculator type from postfix to infix and back by clicking the radio buttons (in the GUI) or
entering 'x' in the command line. By default, the postfix calculator is selected.

Please enter either a postfix or infix expression, with each token separated by a space. For example:

( 1 + 5 ) / 2

8 4 +

If using the ASCII view, change the expression with ? like so:

?( 1 + 5 ) / 2 or

?8 4 +

and enter 'c' to calculate.

## To test
* `mvn test`
* `mvn checkstyle:checkstyle`
